<a href="https://colab.research.google.com/github/bharathbolla/Click-Through-Rate-Prediction/blob/main/CTR_Binary_Classification_Pre_processing.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import random
import pandas as pd
import seaborn as sns

In [ ]:
pip install -U imbalanced-learn

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Requirement already satisfied: imbalanced-learn in /usr/local/lib/python3.7/dist-packages (0.8.1)
Collecting imbalanced-learn
  Downloading imbalanced_learn-0.9.1-py3-none-any.whl (199 kB)
     |████████████████████████████████| 199 kB 4.1 MB/s
Requirement already satisfied: joblib>=1.0.0 in /usr/local/lib/python3.7/dist-packages (from imbalanced-learn) (1.1.0)
Requirement already satisfied: scipy>=1.3.2 in /usr/local/lib/python3.7/dist-packages (from imbalanced-learn) (1.4.1)
Requirement already satisfied: numpy>=1.17.3 in /usr/local/lib/python3.7/dist-packages (from imbalanced-learn) (1.21.6)
Requirement already satisfied: threadpoolctl>=2.0.0 in /usr/local/lib/python3.7/dist-packages (from imbalanced-learn) (3.1.0)
  Downloading imbalanced_learn-0.9.0-py3-none-any.whl (199 kB)
     |████████████████████████████████| 199 kB 20.5 MB/s
Requirement already satisfied: scikit-learn>=1.0.1 in /usr/local/lib/python3.7/dist-packages (from imbalanced-learn) (1.0.2)
Installing collected packages: imbalanced-learn
  Attempting uninstall: imbalanced-learn
    Found existing installation: imbalanced-learn 0.8.1
    Uninstalling imbalanced-learn-0.8.1:
      Successfully uninstalled imbalanced-learn-0.8.1
Successfully installed imbalanced-learn-0.9.0

In [ ]:
pip install mljar-supervised

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Collecting mljar-supervised
  Downloading mljar-supervised-0.11.2.tar.gz (113 kB)
     |████████████████████████████████| 113 kB 4.0 MB/s
Requirement already satisfied: numpy>=1.19.5 in /usr/local/lib/python3.7/dist-packages (from mljar-supervised) (1.21.6)
Requirement already satisfied: pandas>=1.2.0 in /usr/local/lib/python3.7/dist-packages (from mljar-supervised) (1.3.5)
Collecting scipy>=1.6.1
  Downloading scipy-1.7.3-cp37-cp37m-manylinux_2_12_x86_64.manylinux2010_x86_64.whl (38.1 MB)
     |████████████████████████████████| 38.1 MB 1.4 MB/s
Requirement already satisfied: scikit-learn>=1.0 in /usr/local/lib/python3.7/dist-packages (from mljar-supervised) (1.0.2)
Collecting xgboost>=1.3.3
  Downloading xgboost-1.6.1-py3-none-manylinux2014_x86_64.whl (192.9 MB)
     |████████████████████████████████| 192.9 MB 39 kB/s
Collecting lightgbm>=3.0.0
  Downloading lightgbm-3.3.2-py3-none-manylinux1_x86_64.whl (2.0 MB)
     |████████████████████████████████| 2.0 MB 62.0 MB/s
Collecting catboost>=0.24.4
  Downloading catboost-1.0.6-cp37-none-manylinux1_x86_64.whl (76.6 MB)
     |████████████████████████████████| 76.6 MB 119 kB/s
Requirement already satisfied: joblib>=1.0.1 in /usr/local/lib/python3.7/dist-packages (from mljar-supervised) (1.1.0)
Requirement already satisfied: tabulate>=0.8.7 in /usr/local/lib/python3.7/dist-packages (from mljar-supervised) (0.8.9)
Requirement already satisfied: matplotlib>=3.2.2 in /usr/local/lib/python3.7/dist-packages (from mljar-supervised) (3.2.2)
Collecting dtreeviz>=1.3.3
  Downloading dtreeviz-1.3.6.tar.gz (61 kB)
     |████████████████████████████████| 61 kB 161 kB/s
Collecting shap==0.36.0
  Downloading shap-0.36.0.tar.gz (319 kB)
     |████████████████████████████████| 319 kB 67.2 MB/s
Requirement already satisfied: seaborn>=0.11.1 in /usr/local/lib/python3.7/dist-packages (from mljar-supervised) (0.11.2)
Collecting wordcloud>=1.8.1
  Downloading wordcloud-1.8.1-cp37-cp37m-manylinux1_x86_64.whl (366 kB)
     |████████████████████████████████| 366 kB 63.2 MB/s
Collecting category_encoders>=2.2.2
  Downloading category_encoders-2.4.1-py2.py3-none-any.whl (80 kB)
     |████████████████████████████████| 80 kB 8.3 MB/s
Collecting optuna>=2.7.0
  Downloading optuna-2.10.0-py3-none-any.whl (308 kB)
     |████████████████████████████████| 308 kB 73.1 MB/s
Collecting scikit-plot==0.3.7
  Downloading scikit_plot-0.3.7-py3-none-any.whl (33 kB)
Requirement already satisfied: markdown in /usr/local/lib/python3.7/dist-packages (from mljar-supervised) (3.3.7)
Requirement already satisfied: typing-extensions in /usr/local/lib/python3.7/dist-packages (from mljar-supervised) (4.2.0)
Requirement already satisfied: tqdm>4.25.0 in /usr/local/lib/python3.7/dist-packages (from shap==0.36.0->mljar-supervised) (4.64.0)
Collecting slicer
  Downloading slicer-0.0.7-py3-none-any.whl (14 kB)
Requirement already satisfied: numba in /usr/local/lib/python3.7/dist-packages (from shap==0.36.0->mljar-supervised) (0.51.2)
Requirement already satisfied: plotly in /usr/local/lib/python3.7/dist-packages (from catboost>=0.24.4->mljar-supervised) (5.5.0)
Requirement already satisfied: six in /usr/local/lib/python3.7/dist-packages (from catboost>=0.24.4->mljar-supervised) (1.15.0)
Requirement already satisfied: graphviz in /usr/local/lib/python3.7/dist-packages (from catboost>=0.24.4->mljar-supervised) (0.10.1)
Requirement already satisfied: statsmodels>=0.9.0 in /usr/local/lib/python3.7/dist-packages (from category_encoders>=2.2.2->mljar-supervised) (0.10.2)
Requirement already satisfied: patsy>=0.5.1 in /usr/local/lib/python3.7/dist-packages (from category_encoders>=2.2.2->mljar-supervised) (0.5.2)
Collecting colour
  Downloading colour-0.1.5-py2.py3-none-any.whl (23 kB)
Requirement already satisfied: pytest in /usr/local/lib/python3.7/dist-packages (from dtreeviz>=1.3.3->mljar-supervised) (3.6.4)
Requirement already satisfied: wheel in /usr/local/lib/python3.7/dist-packages (from lightgbm>=3.0.0->mljar-supervised) (0.37.1)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.7/dist-packages (from matplotlib>=3.2.2->mljar-supervised) (0.11.0)
Requirement already satisfied: pyparsing!=2.0.4,!=2.1.2,!=2.1.6,>=2.0.1 in /usr/local/lib/python3.7/dist-packages (from matplotlib>=3.2.2->mljar-supervised) (3.0.9)
Requirement already satisfied: kiwisolver>=1.0.1 in /usr/local/lib/python3.7/dist-packages (from matplotlib>=3.2.2->mljar-supervised) (1.4.2)
Requirement already satisfied: python-dateutil>=2.1 in /usr/local/lib/python3.7/dist-packages (from matplotlib>=3.2.2->mljar-supervised) (2.8.2)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.7/dist-packages (from optuna>=2.7.0->mljar-supervised) (21.3)
Requirement already satisfied: PyYAML in /usr/local/lib/python3.7/dist-packages (from optuna>=2.7.0->mljar-supervised) (3.13)
Collecting cmaes>=0.8.2
  Downloading cmaes-0.8.2-py3-none-any.whl (15 kB)
Collecting cliff
  Downloading cliff-3.10.1-py3-none-any.whl (81 kB)
     |████████████████████████████████| 81 kB 7.1 MB/s
Requirement already satisfied: sqlalchemy>=1.1.0 in /usr/local/lib/python3.7/dist-packages (from optuna>=2.7.0->mljar-supervised) (1.4.36)
Collecting colorlog
  Downloading colorlog-6.6.0-py2.py3-none-any.whl (11 kB)
Collecting alembic
  Downloading alembic-1.7.7-py3-none-any.whl (210 kB)
     |████████████████████████████████| 210 kB 55.2 MB/s
Requirement already satisfied: pytz>=2017.3 in /usr/local/lib/python3.7/dist-packages (from pandas>=1.2.0->mljar-supervised) (2022.1)
Requirement already satisfied: threadpoolctl>=2.0.0 in /usr/local/lib/python3.7/dist-packages (from scikit-learn>=1.0->mljar-supervised) (3.1.0)
Requirement already satisfied: greenlet!=0.4.17 in /usr/local/lib/python3.7/dist-packages (from sqlalchemy>=1.1.0->optuna>=2.7.0->mljar-supervised) (1.1.2)
Requirement already satisfied: importlib-metadata in /usr/local/lib/python3.7/dist-packages (from sqlalchemy>=1.1.0->optuna>=2.7.0->mljar-supervised) (4.11.3)
Requirement already satisfied: pillow in /usr/local/lib/python3.7/dist-packages (from wordcloud>=1.8.1->mljar-supervised) (7.1.2)
Collecting Mako
  Downloading Mako-1.2.0-py3-none-any.whl (78 kB)
     |████████████████████████████████| 78 kB 5.3 MB/s
Requirement already satisfied: importlib-resources in /usr/local/lib/python3.7/dist-packages (from alembic->optuna>=2.7.0->mljar-supervised) (5.7.1)
Collecting cmd2>=1.0.0
  Downloading cmd2-2.4.1-py3-none-any.whl (146 kB)
     |████████████████████████████████| 146 kB 56.5 MB/s
Collecting pbr!=2.1.0,>=2.0.0
  Downloading pbr-5.9.0-py2.py3-none-any.whl (112 kB)
     |████████████████████████████████| 112 kB 72.4 MB/s
Requirement already satisfied: PrettyTable>=0.7.2 in /usr/local/lib/python3.7/dist-packages (from cliff->optuna>=2.7.0->mljar-supervised) (3.3.0)
Collecting stevedore>=2.0.1
  Downloading stevedore-3.5.0-py3-none-any.whl (49 kB)
     |████████████████████████████████| 49 kB 4.9 MB/s
Collecting autopage>=0.4.0
  Downloading autopage-0.5.1-py3-none-any.whl (29 kB)
Collecting pyperclip>=1.6
  Downloading pyperclip-1.8.2.tar.gz (20 kB)
Requirement already satisfied: wcwidth>=0.1.7 in /usr/local/lib/python3.7/dist-packages (from cmd2>=1.0.0->cliff->optuna>=2.7.0->mljar-supervised) (0.2.5)
Requirement already satisfied: attrs>=16.3.0 in /usr/local/lib/python3.7/dist-packages (from cmd2>=1.0.0->cliff->optuna>=2.7.0->mljar-supervised) (21.4.0)
Requirement already satisfied: zipp>=0.5 in /usr/local/lib/python3.7/dist-packages (from importlib-metadata->sqlalchemy>=1.1.0->optuna>=2.7.0->mljar-supervised) (3.8.0)
Requirement already satisfied: MarkupSafe>=0.9.2 in /usr/local/lib/python3.7/dist-packages (from Mako->alembic->optuna>=2.7.0->mljar-supervised) (2.0.1)
Requirement already satisfied: setuptools in /usr/local/lib/python3.7/dist-packages (from numba->shap==0.36.0->mljar-supervised) (57.4.0)
Requirement already satisfied: llvmlite<0.35,>=0.34.0.dev0 in /usr/local/lib/python3.7/dist-packages (from numba->shap==0.36.0->mljar-supervised) (0.34.0)
Requirement already satisfied: tenacity>=6.2.0 in /usr/local/lib/python3.7/dist-packages (from plotly->catboost>=0.24.4->mljar-supervised) (8.0.1)
Requirement already satisfied: atomicwrites>=1.0 in /usr/local/lib/python3.7/dist-packages (from pytest->dtreeviz>=1.3.3->mljar-supervised) (1.4.0)
Requirement already satisfied: more-itertools>=4.0.0 in /usr/local/lib/python3.7/dist-packages (from pytest->dtreeviz>=1.3.3->mljar-supervised) (8.13.0)
Requirement already satisfied: py>=1.5.0 in /usr/local/lib/python3.7/dist-packages (from pytest->dtreeviz>=1.3.3->mljar-supervised) (1.11.0)
Requirement already satisfied: pluggy<0.8,>=0.5 in /usr/local/lib/python3.7/dist-packages (from pytest->dtreeviz>=1.3.3->mljar-supervised) (0.7.1)
Building wheels for collected packages: mljar-supervised, shap, dtreeviz, pyperclip
  Building wheel for mljar-supervised (setup.py) ... done
  Created wheel for mljar-supervised: filename=mljar_supervised-0.11.2-py3-none-any.whl size=146575 sha256=0d31a98ca2c297a372a71b438bd9d6673d4c12c7962ae07f01521ee3fb6d20e5
  Stored in directory: /root/.cache/pip/wheels/4f/67/ed/479dbde33806ee15f1611a7ff54b9db565076be8acf2ef2d29
  Building wheel for shap (setup.py) ... done
  Created wheel for shap: filename=shap-0.36.0-cp37-cp37m-linux_x86_64.whl size=457667 sha256=1f47aa6e3c1d52246013e53e485e05891e8eb98b43d7c14f466dc4b189c36a48
  Stored in directory: /root/.cache/pip/wheels/6b/1e/4a/b1d65778aac48b677ac2a758251f9cccb338775e8d174f3696
  Building wheel for dtreeviz (setup.py) ... done
  Created wheel for dtreeviz: filename=dtreeviz-1.3.6-py3-none-any.whl size=67326 sha256=42cfb098eb9401b25bfb7483ff23898c1f0d5e4a3ecb790c3d38e73c16ff1ab2
  Stored in directory: /root/.cache/pip/wheels/33/76/fe/99227ff871766e7284bb88d3d28e2f4886b8ec04d669033478
  Building wheel for pyperclip (setup.py) ... done
  Created wheel for pyperclip: filename=pyperclip-1.8.2-py3-none-any.whl size=11137 sha256=29ee5d4e66467643117f3a33582f2c15e87894c902679b8be8570e2c55d54bb6
  Stored in directory: /root/.cache/pip/wheels/9f/18/84/8f69f8b08169c7bae2dde6bd7daf0c19fca8c8e500ee620a28
Successfully built mljar-supervised shap dtreeviz pyperclip
Installing collected packages: pyperclip, pbr, stevedore, scipy, Mako, cmd2, autopage, slicer, colour, colorlog, cmaes, cliff, alembic, xgboost, wordcloud, shap, scikit-plot, optuna, lightgbm, dtreeviz, category-encoders, catboost, mljar-supervised
  Attempting uninstall: scipy
    Found existing installation: scipy 1.4.1
    Uninstalling scipy-1.4.1:
      Successfully uninstalled scipy-1.4.1
  Attempting uninstall: xgboost
    Found existing installation: xgboost 0.90
    Uninstalling xgboost-0.90:
      Successfully uninstalled xgboost-0.90
  Attempting uninstall: wordcloud
    Found existing installation: wordcloud 1.5.0
    Uninstalling wordcloud-1.5.0:
      Successfully uninstalled wordcloud-1.5.0
  Attempting uninstall: lightgbm
    Found existing installation: lightgbm 2.2.3
    Uninstalling lightgbm-2.2.3:
      Successfully uninstalled lightgbm-2.2.3
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
albumentations 0.1.12 requires imgaug<0.2.7,>=0.2.5, but you have imgaug 0.2.9 which is incompatible.
Successfully installed Mako-1.2.0 alembic-1.7.7 autopage-0.5.1 catboost-1.0.6 category-encoders-2.4.1 cliff-3.10.1 cmaes-0.8.2 cmd2-2.4.1 colorlog-6.6.0 colour-0.1.5 dtreeviz-1.3.6 lightgbm-3.3.2 mljar-supervised-0.11.2 optuna-2.10.0 pbr-5.9.0 pyperclip-1.8.2 scikit-plot-0.3.7 scipy-1.7.3 shap-0.36.0 slicer-0.0.7 stevedore-3.5.0 wordcloud-1.8.1 xgboost-1.6.1

In [ ]:
pd.set_option('display.max_columns', None)
pd.set_option('display.expand_frame_repr', False)
pd.set_option('max_colwidth', -1)

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:3: FutureWarning: Passing a negative integer is deprecated in version 1.0 and will not be supported in future version. Instead, use None to not limit the column width.
  This is separate from the ipykernel package so we can avoid doing imports until

In [ ]:
df  = pd.read_csv("data.csv")

In [ ]:
df.head()

   click    C1  banner_pos   site_id site_domain site_category    app_id app_domain app_category device_id device_ip device_model  device_type  device_conn_type    C14  C15  C16   C17  C18  C19     C20  C21  month  dayofweek  day  hour  y
0  False  1005  1           856e6d3f  58a89a43    f028772b      ecad2386  7801e8d9   07d7df22     a99f214a  962c8333  be6db1d7     1            0                 22683  320  50   2528  0    39   100075  221  10     1          28   14    0
1  True   1005  1           e151e245  7e091613    f028772b      ecad2386  7801e8d9   07d7df22     a99f214a  5b1f94b9  1b13b020     1            0                 17037  320  50   1934  2    39  -1       16   10     2          22   19    1
2  False  1005  0           e3c09f3a  d262cf1e    28905ebd      ecad2386  7801e8d9   07d7df22     a99f214a  a9a84f4c  9a45a8e8     1            0                 22155  320  50   2552  3    167  100202  23   10     3          23   18    0
3  False  1002  0           0da94452  248e439f    50e219e0      ecad2386  7801e8d9   07d7df22     0fa578fd  88c62dad  ea6abc60     0            0                 21591  320  50   2478  3    167  100074  23   10     2          22   19    0
4  True   1005  0           1fbe01fe  f3845767    28905ebd      ecad2386  7801e8d9   07d7df22     a99f214a  1e5e0d0e  36d749e5     1            0                 15708  320  50   1722  0    35  -1       79   10     1          21   8     1

In [ ]:
df.info(show_counts=True)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 99999 entries, 0 to 99998
Data columns (total 27 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   click             99999 non-null  bool
 1   C1                99999 non-null  int64
 2   banner_pos        99999 non-null  int64
 3   site_id           99999 non-null  object
 4   site_domain       99999 non-null  object
 5   site_category     99999 non-null  object
 6   app_id            99999 non-null  object
 7   app_domain        99999 non-null  object
 8   app_category      99999 non-null  object
 9   device_id         99999 non-null  object
 10  device_ip         99999 non-null  object
 11  device_model      99999 non-null  object
 12  device_type       99999 non-null  int64
 13  device_conn_type  99999 non-null  int64
 14  C14               99999 non-null  int64
 15  C15               99999 non-null  int64
 16  C16               99999 non-null  int64
 17  C17               99999 non-null  int64
 18  C18               99999 non-null  int64
 19  C19               99999 non-null  int64
 20  C20               99999 non-null  int64
 21  C21               99999 non-null  int64
 22  month             99999 non-null  int64
 23  dayofweek         99999 non-null  int64
 24  day               99999 non-null  int64
 25  hour              99999 non-null  int64
 26  y                 99999 non-null  int64
dtypes: bool(1), int64(17), object(9)
memory usage: 19.9+ MB

In [ ]:
df.describe()

                 C1    banner_pos  device_type  device_conn_type           C14           C15           C16           C17           C18           C19            C20           C21    month     dayofweek           day          hour             y
count  99999.000000  99999.000000  99999.00000  99999.000000      99999.000000  99999.000000  99999.000000  99999.000000  99999.000000  99999.000000  99999.000000   99999.000000  99999.0  99999.000000  99999.000000  99999.000000  99999.000000
mean   1004.967550   0.289943      1.01639      0.329453          18857.231732  318.834548    60.278743     2114.613036   1.439904      227.234932    53292.001950   83.163542     10.0     2.592836      25.485755     11.300673     0.169802
std    1.091916      0.505707      0.53110      0.854673          4944.919482   21.510752     47.713436     607.469442    1.326824      351.472366    49952.340367   70.161076     0.0      1.723003      2.968520      5.938725      0.375460
min    1001.000000   0.000000      0.00000      0.000000          375.000000    120.000000    20.000000     112.000000    0.000000      33.000000    -1.000000       1.000000      10.0     0.000000      21.000000     0.000000      0.000000
25%    1005.000000   0.000000      1.00000      0.000000          16920.000000  320.000000    50.000000     1863.000000   0.000000      35.000000    -1.000000       23.000000     10.0     1.000000      23.000000     7.000000      0.000000
50%    1005.000000   0.000000      1.00000      0.000000          20346.000000  320.000000    50.000000     2323.000000   2.000000      39.000000     100050.000000  61.000000     10.0     2.000000      26.000000     11.000000     0.000000
75%    1005.000000   1.000000      1.00000      0.000000          21893.000000  320.000000    50.000000     2526.000000   3.000000      171.000000    100093.000000  101.000000    10.0     4.000000      28.000000     16.000000     0.000000
max    1012.000000   7.000000      5.00000      5.000000          24043.000000  1024.000000   1024.000000   2757.000000   3.000000      1839.000000   100248.000000  255.000000    10.0     6.000000      30.000000     23.000000     1.000000

In [ ]:
df.describe(include="all")

        click            C1    banner_pos   site_id site_domain site_category    app_id app_domain app_category device_id device_ip device_model  device_type  device_conn_type           C14           C15           C16           C17           C18           C19            C20           C21    month     dayofweek           day          hour             y
count   99999  99999.000000  99999.000000  99999     99999       99999         99999     99999      99999        99999     99999     99999        99999.00000  99999.000000      99999.000000  99999.000000  99999.000000  99999.000000  99999.000000  99999.000000  99999.000000   99999.000000  99999.0  99999.000000  99999.000000  99999.000000  99999.000000
unique  2     NaN           NaN            1485      1331        19            1354      96         21           16801     78013     3145        NaN          NaN               NaN           NaN           NaN           NaN           NaN           NaN           NaN            NaN           NaN      NaN           NaN           NaN           NaN
top     False NaN           NaN            85f751fd  c4e18dd6    50e219e0      ecad2386  7801e8d9   07d7df22     a99f214a  6b9769f2  8a4875bd    NaN          NaN               NaN           NaN           NaN           NaN           NaN           NaN           NaN            NaN           NaN      NaN           NaN           NaN           NaN
freq    83019 NaN           NaN            36022     37362       40839         63977     67464      64769        82579     521       6041        NaN          NaN               NaN           NaN           NaN           NaN           NaN           NaN           NaN            NaN           NaN      NaN           NaN           NaN           NaN
mean    NaN    1004.967550   0.289943      NaN       NaN         NaN           NaN       NaN        NaN          NaN       NaN       NaN          1.01639      0.329453          18857.231732  318.834548    60.278743     2114.613036   1.439904      227.234932    53292.001950   83.163542     10.0     2.592836      25.485755     11.300673     0.169802
std     NaN    1.091916      0.505707      NaN       NaN         NaN           NaN       NaN        NaN          NaN       NaN       NaN          0.53110      0.854673          4944.919482   21.510752     47.713436     607.469442    1.326824      351.472366    49952.340367   70.161076     0.0      1.723003      2.968520      5.938725      0.375460
min     NaN    1001.000000   0.000000      NaN       NaN         NaN           NaN       NaN        NaN          NaN       NaN       NaN          0.00000      0.000000          375.000000    120.000000    20.000000     112.000000    0.000000      33.000000    -1.000000       1.000000      10.0     0.000000      21.000000     0.000000      0.000000
25%     NaN    1005.000000   0.000000      NaN       NaN         NaN           NaN       NaN        NaN          NaN       NaN       NaN          1.00000      0.000000          16920.000000  320.000000    50.000000     1863.000000   0.000000      35.000000    -1.000000       23.000000     10.0     1.000000      23.000000     7.000000      0.000000
50%     NaN    1005.000000   0.000000      NaN       NaN         NaN           NaN       NaN        NaN          NaN       NaN       NaN          1.00000      0.000000          20346.000000  320.000000    50.000000     2323.000000   2.000000      39.000000     100050.000000  61.000000     10.0     2.000000      26.000000     11.000000     0.000000
75%     NaN    1005.000000   1.000000      NaN       NaN         NaN           NaN       NaN        NaN          NaN       NaN       NaN          1.00000      0.000000          21893.000000  320.000000    50.000000     2526.000000   3.000000      171.000000    100093.000000  101.000000    10.0     4.000000      28.000000     16.000000     0.000000
max     NaN    1012.000000   7.000000      NaN       NaN         NaN           NaN       NaN        NaN          NaN       NaN       NaN          5.00000      5.000000          24043.000000  1024.000000   1024.000000   2757.000000   3.000000      1839.000000   100248.000000  255.000000    10.0     6.000000      30.000000     23.000000     1.000000

### Changing Data Types
####  "banner_pos",  and "C1", "device_type", "device_conn_type", "C14 - C21", "month", "day of week", "day", hour" are categorical variables

In [ ]:
convert_cols_list = ["banner_pos", "C1", "device_type", "device_conn_type", "C14", "C15", "C16", "C17", "C18", "C19", "C20", "C21", "month", "dayofweek", "day", "hour"]

In [ ]:
def convert_datatype(col_list, data):
  for col in col_list:
    data[col] = data[col].astype('category')
  return data

In [ ]:
df_new = convert_datatype(convert_cols_list, df)
df_new.dtypes

click               bool
C1                  category
banner_pos          category
site_id             object
site_domain         object
site_category       object
app_id              object
app_domain          object
app_category        object
device_id           object
device_ip           object
device_model        object
device_type         category
device_conn_type    category
C14                 category
C15                 category
C16                 category
C17                 category
C18                 category
C19                 category
C20                 category
C21                 category
month               category
dayofweek           category
day                 category
hour                category
y                   int64
dtype: object

In [ ]:
df_new.describe(include = 'all')

        click       C1  banner_pos   site_id site_domain site_category    app_id app_domain app_category device_id device_ip device_model  device_type  device_conn_type      C14      C15      C16      C17      C18      C19      C20      C21    month  dayofweek      day     hour             y
count   99999  99999.0  99999.0     99999     99999       99999         99999     99999      99999        99999     99999     99999        99999.0      99999.0           99999.0  99999.0  99999.0  99999.0  99999.0  99999.0  99999.0  99999.0  99999.0  99999.0    99999.0  99999.0  99999.000000
unique  2      7.0      7.0         1485      1331        19            1354      96         21           16801     78013     3145         4.0          4.0               1722.0   8.0      9.0      399.0    4.0      64.0     154.0    60.0     1.0      7.0        10.0     24.0    NaN
top     False  1005.0   0.0         85f751fd  c4e18dd6    50e219e0      ecad2386  7801e8d9   07d7df22     a99f214a  6b9769f2  8a4875bd     1.0          0.0               4687.0   320.0    50.0     1722.0   0.0      35.0    -1.0      23.0     10.0     1.0        22.0     13.0    NaN
freq    83019  91862.0  71778.0     36022     37362       40839         63977     67464      64769        82579     521       6041         92239.0      86413.0           2306.0   93136.0  94209.0  10991.0  41659.0  29935.0  46767.0  22096.0  99999.0  23269.0    13092.0  5905.0  NaN
mean    NaN   NaN      NaN          NaN       NaN         NaN           NaN       NaN        NaN          NaN       NaN       NaN         NaN          NaN               NaN      NaN      NaN      NaN      NaN      NaN      NaN      NaN      NaN      NaN        NaN      NaN       0.169802
std     NaN   NaN      NaN          NaN       NaN         NaN           NaN       NaN        NaN          NaN       NaN       NaN         NaN          NaN               NaN      NaN      NaN      NaN      NaN      NaN      NaN      NaN      NaN      NaN        NaN      NaN       0.375460
min     NaN   NaN      NaN          NaN       NaN         NaN           NaN       NaN        NaN          NaN       NaN       NaN         NaN          NaN               NaN      NaN      NaN      NaN      NaN      NaN      NaN      NaN      NaN      NaN        NaN      NaN       0.000000
25%     NaN   NaN      NaN          NaN       NaN         NaN           NaN       NaN        NaN          NaN       NaN       NaN         NaN          NaN               NaN      NaN      NaN      NaN      NaN      NaN      NaN      NaN      NaN      NaN        NaN      NaN       0.000000
50%     NaN   NaN      NaN          NaN       NaN         NaN           NaN       NaN        NaN          NaN       NaN       NaN         NaN          NaN               NaN      NaN      NaN      NaN      NaN      NaN      NaN      NaN      NaN      NaN        NaN      NaN       0.000000
75%     NaN   NaN      NaN          NaN       NaN         NaN           NaN       NaN        NaN          NaN       NaN       NaN         NaN          NaN               NaN      NaN      NaN      NaN      NaN      NaN      NaN      NaN      NaN      NaN        NaN      NaN       0.000000
max     NaN   NaN      NaN          NaN       NaN         NaN           NaN       NaN        NaN          NaN       NaN       NaN         NaN          NaN               NaN      NaN      NaN      NaN      NaN      NaN      NaN      NaN      NaN      NaN        NaN      NaN       1.000000

### Check nunique values to see of all categorical features are relavent

In [ ]:
df_nunique = df_new.describe(include = 'all').T.unique
df_nunique

click               2
C1                  7.0
banner_pos          7.0
site_id             1485
site_domain         1331
site_category       19
app_id              1354
app_domain          96
app_category        21
device_id           16801
device_ip           78013
device_model        3145
device_type         4.0
device_conn_type    4.0
C14                 1722.0
C15                 8.0
C16                 9.0
C17                 399.0
C18                 4.0
C19                 64.0
C20                 154.0
C21                 60.0
month               1.0
dayofweek           7.0
day                 10.0
hour                24.0
y                   NaN
Name: unique, dtype: object

## CE Benchmark

In [ ]:
!pip install category-encoders

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Requirement already satisfied: category-encoders in /usr/local/lib/python3.7/dist-packages (2.4.1)
Requirement already satisfied: scikit-learn>=0.20.0 in /usr/local/lib/python3.7/dist-packages (from category-encoders) (1.0.2)
Requirement already satisfied: pandas>=0.21.1 in /usr/local/lib/python3.7/dist-packages (from category-encoders) (1.3.5)
Requirement already satisfied: patsy>=0.5.1 in /usr/local/lib/python3.7/dist-packages (from category-encoders) (0.5.2)
Requirement already satisfied: statsmodels>=0.9.0 in /usr/local/lib/python3.7/dist-packages (from category-encoders) (0.10.2)
Requirement already satisfied: scipy>=1.0.0 in /usr/local/lib/python3.7/dist-packages (from category-encoders) (1.7.3)
Requirement already satisfied: numpy>=1.14.0 in /usr/local/lib/python3.7/dist-packages (from category-encoders) (1.21.6)
Requirement already satisfied: python-dateutil>=2.7.3 in /usr/local/lib/python3.7/dist-packages (from pandas>=0.21.1->category-encoders) (2.8.2)
Requirement already satisfied: pytz>=2017.3 in /usr/local/lib/python3.7/dist-packages (from pandas>=0.21.1->category-encoders) (2022.1)
Requirement already satisfied: six in /usr/local/lib/python3.7/dist-packages (from patsy>=0.5.1->category-encoders) (1.15.0)
Requirement already satisfied: joblib>=0.11 in /usr/local/lib/python3.7/dist-packages (from scikit-learn>=0.20.0->category-encoders) (1.1.0)
Requirement already satisfied: threadpoolctl>=2.0.0 in /usr/local/lib/python3.7/dist-packages (from scikit-learn>=0.20.0->category-encoders) (3.1.0)

In [ ]:
# import required packages
from pathlib import Path
from pprint import pprint
from joblib import dump, load
from collections import OrderedDict
from IPython.display import display, Markdown, Latex, HTML
from pandas.api.types import is_datetime64_any_dtype as is_datetime



import os
import time
import pickle
import datetime
import warnings
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
import category_encoders as ce


from sklearn.linear_model import LogisticRegression
from sklearn.naive_bayes import BernoulliNB
from sklearn.neighbors import KNeighborsClassifier
from sklearn.svm import SVC
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier, ExtraTreesClassifier
from sklearn.pipeline import make_pipeline
from sklearn.pipeline import Pipeline
from sklearn.impute import SimpleImputer
from sklearn.compose import ColumnTransformer
from xgboost import XGBClassifier
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.model_selection import cross_val_score
import sklearn.metrics as skm
from sklearn.ensemble import GradientBoostingClassifier
from sklearn.ensemble import AdaBoostClassifier
from sklearn.gaussian_process.kernels import RBF
from sklearn import set_config
from sklearn.utils import estimator_html_repr


import plotly.graph_objects as go
from plotly.subplots import make_subplots
import plotly.figure_factory as ff
import plotly.express as px

rs = {'random_state': 42}


from sklearn.compose import make_column_selector as selector

/usr/local/lib/python3.7/dist-packages/statsmodels/tools/_testing.py:19: FutureWarning: pandas.util.testing is deprecated. Use the functions in the public API at pandas.testing instead.
  import pandas.util.testing as tm

In [ ]:
def returnCatNumList(df):
    
    object_cols = list(df.select_dtypes(exclude=np.number).columns)
    numeric_cols = list(df.select_dtypes(include=np.number).columns)

    return object_cols, numeric_cols

# cat_cols, num_cols = returnCatNumList(diamonds)


def get_model_metrics(y_test, y_pred):

    # F1-Score
    fscore = skm.f1_score(y_test, y_pred)
    # Precision
    pres = skm.precision_score(y_test, y_pred)
    # Recall
    rcall = skm.recall_score(y_test, y_pred)
    # Accuracy
    accu = skm.accuracy_score(y_test, y_pred)
    # ROC_AUC
    roc_auc = skm.roc_auc_score(y_test, y_pred)

    return fscore, pres, rcall, accu, roc_auc



def categorical_encoding_benchmark(X, y, num_cols):


    # cat enc instances
    encoder_cat = ce.CatBoostEncoder()
    encoder_cnt = ce.CountEncoder()
    encoder_loo = ce.LeaveOneOutEncoder()
    #encoder_ohe = ce.OneHotEncoder()
    encoder_ord = ce.OrdinalEncoder()
    encoder_tar = ce.TargetEncoder()
    encoder_woe = ce.WOEEncoder()

    print("----------------------------->> Category Encoders instances created")

    encoders_list = [
                     ("CatBoostEncoder", encoder_cat),
                     ("CountEncoder", encoder_cnt),
                     ("LeaveOneOutEncoder", encoder_loo), 
                     #("OneHotEncoder", encoder_ohe), 
                     ("OrdinalEncoder", encoder_ord),
                     ("TargetEncoder",encoder_tar), 
                     ("WOEEncoder",encoder_woe)]


    log_reg = LogisticRegression(solver='lbfgs',
                                 max_iter=10000,
                                 **rs)
    dt = DecisionTreeClassifier(**rs)
    rf = RandomForestClassifier(**rs)
    xgb = XGBClassifier(**rs, 
                        verbosity=0, 
                        use_label_encoder=False)


    clfs = [
            ('Logistic Regression', log_reg), 
            ('Random Forest', rf), 
            ('XGBoost', xgb)
            ]

    print("------------------------------------->> ML Models instances created")
    pipelines = {
                 'CatBoostEncoder': [], 
                 'CountEncoder': [],
                 'LeaveOneOutEncoder': [],
                 #'OneHotEncoder': [], 
                 'OrdinalEncoder': [], 
                 'TargetEncoder': [], 
                 'WOEEncoder': []}

    scores_df = pd.DataFrame(columns=['Categorical_Encoder', 'Model', 'F1_Score', 
                                      'Precision', 'Recall', 'Accuracy', 'ROC_AUC',
                                      'Timetaken_to_Mdl(secs)'])
    



    # Train-test Split
    X_train, X_test, y_train, y_test = train_test_split(X, 
                                                        y, 
                                                        test_size = 0.30, 
                                                        random_state = 42,  stratify =y)
    print("Data Split --------------------->> X_train, X_test, y_train, y_test")
    
    from imblearn.over_sampling import RandomOverSampler
    randomsample=  RandomOverSampler()
    X_train,y_train=randomsample.fit_resample(X_train,y_train)

    
    for encoder_name, encoder in encoders_list:

        print(encoder_name)


        numeric_preprocessor = Pipeline(
            steps=[
                   ("imputation_mean", SimpleImputer(missing_values=np.nan, 
                                                     strategy="mean")),
                   ("scaler", StandardScaler()),
            ]
        )

        categorical_preprocessor = Pipeline(
            steps=[
                   ("imputation_constant",
                    SimpleImputer(fill_value="missing", strategy="constant"),
                ),
                (encoder_name, encoder),
            ]
        )


        numerical_columns_selector = selector(dtype_exclude=object)
        categorical_columns_selector = selector(dtype_include=object)

        numerical_columns = numerical_columns_selector(X)
        categorical_columns = categorical_columns_selector(X)

        preprocessor = ColumnTransformer(
            [
                ("categorical", categorical_preprocessor, categorical_columns),
                ("numerical", numeric_preprocessor, numerical_columns),
            ]
        )

        
        for clf_name, clf in clfs:

            clf_start_time = time.time()

            print(clf_name)

            pipeline = Pipeline(
                steps=[
                       ("preprocessor", preprocessor), 
                       ("classifier", clf)
                       ]
            )


            pipeline.fit(X_train, y_train)


            y_pred = pipeline.predict(X_test)

            
            fscore, pres, rcall, accu, roc_auc = get_model_metrics(y_test, y_pred)


            # break
            time_taken_to_mdl = time.time() - clf_start_time
            # time_fmt = time.strftime("%H:%M:%S",time.gmtime(seconds))

            pipelines[encoder_name].append(pipeline)
                
            scores_dict = {
                'Categorical_Encoder': encoder_name,
                'Model' : clf_name, 
                'F1_Score' : fscore,
                'Precision' : pres,
                'Recall' : rcall,
                'Accuracy' : accu,
                'ROC_AUC' : roc_auc,
                'Timetaken_to_Mdl(secs)':time_taken_to_mdl
                }
            
            scores_df = pd.concat([scores_df, pd.DataFrame.from_records([scores_dict])])

            print("--------------------------->> Evaluation of Model completed")

            print(f"ML Pipeline Successfully----------------->> {encoder_name}")
        
        print("--------------------->>>>>>>Successfully completed CE Benchmark")
            
    return pipelines, scores_df



def summary_benchmark_models(scores_df, color_discrete_map, filename):


    fig = px.bar(
        scores_df,
        y="Model",
        x="F1_Score",
        color="Categorical_Encoder",
        color_discrete_map=color_discrete_map,
        custom_data=['Precision', 'Recall',
                    'Accuracy', 'ROC_AUC'],
        orientation='h'
        )

    fig.update_traces(
        texttemplate="%{x:.2f}",
        textposition="inside",
        insidetextanchor="middle",
        hovertemplate="<br>".join(
            ["Model: %{y}",
            "F1 Score: %{x:.2f}",
            "Precision: %{customdata[0]:.2f}",
            "Recall: %{customdata[1]:.2f}",
            "Accuracy: %{customdata[2]:.2f}",
            "ROC_AUC: %{customdata[3]:.2f}"]
                )
        )

    fig.update_layout(
        title = {'text': "Summary Metrics",
                'x':0.5, 
                'xanchor': 'center'},
        title_font_size=20,
        yaxis=dict(
            title='Models',
            titlefont_size=16
            ),
        hoverlabel=dict(
            bgcolor="white",
            font_size=16,
            font_family="Rockwell"
        ),
        xaxis=dict(
            title="F1-Score",
            titlefont_size=16,

        ),
        legend_title="Categorical Encoders",
        height=600,


    )

    # fig.show()
    fig.write_html(f"CE_BenchMark/Figures/Plotly/{filename}.html")


def CE_BenchMark_Pipeline(datasets, targets):

    #---------------------------------------------------------------------------
    # Create required folders
    Path(f"CE_BenchMark/Figures/Plotly/").mkdir(parents=True, 
                                exist_ok=True)
    
    Path(f"CE_BenchMark/Pipelines/").mkdir(parents=True, 
                                           exist_ok=True)

    Path(f"CE_BenchMark/Scores/").mkdir(parents=True, 
                                        exist_ok=True)

    Path(f"CE_BenchMark/Metadata/").mkdir(parents=True, 
                                        exist_ok=True)
    #---------------------------------------------------------------------------

    file_trail = f"{str(now.day)}_{str(now.month)}_{str(now.year)}_{str(now.hour)}_{str(now.minute)}_{str(now.second)}_"


    pipeline_dict = OrderedDict()
    #---------------------------------------------------------------------------

    metadata  = OrderedDict()

    for df_name, df in datasets.items():

        print(df_name)

        

        # try:

        # Drop datetime
        date_cols = [col for col in df.columns if is_datetime(col)]

        if len(date_cols) > 0:
            data = df.drop(columns=date_cols, errors=False)
        else:
            data = df.copy()

        tar = targets[df_name]
        
        cat_cols, num_cols = returnCatNumList(data)

        num_cols.remove(tar)

    #---------------------------------------------------------------------------

        

        X = data.drop(columns=tar)
        y = data[tar]

        
        pipelines, scores_df = categorical_encoding_benchmark(X, y, num_cols)




        print(f"---------->> Categorical Benchmark completed for {df_name}")

        dump(pipelines,f"CE_BenchMark/Pipelines/{df_name}_{file_trail}.joblib")

        # scores_df.to_csv(f"CE_BenchMark/Scores/{file}_{file_trail}.csv", index=False)

        cm = sns.color_palette("Set2", as_cmap=True)
        
        with pd.ExcelWriter(f"CE_BenchMark/Scores/Scores_styled_{file_trail}.xlsx") as writer:  
            # scores_df.to_excel(writer, sheet_name=file)
            scores_df.set_index(
                ['Categorical_Encoder','Model']
                ).style.background_gradient(cmap=cm).to_excel(
                                writer,
                                sheet_name=df_name
                                )


        fig_sv_name = f"{df_name}_{file_trail}"
        colors_ = "#66C5CC,#F6CF71,#F89C74,#DCB0F2,#87C55F,#9EB9F3,#FE88B1,#C9DB74,#8BE0A4,#B497E7,#D3B484,#B3B3B3,#39b185,#9ccb86,#e9e29c,#eeb479,#e88471"
        colors = colors_.split(",")
        col_values = scores_df['Categorical_Encoder'].unique()
        color_discrete_map = dict(zip(col_values, colors[: len(col_values)]))
        summary_benchmark_models(scores_df, color_discrete_map, fig_sv_name)
        print(scores_df)
        cate_prop = len(cat_cols)/X.shape[1]
        num_prop = len(num_cols)/X.shape[1]

        meta = {"Dataset":df_name,
                # "TimeTaken(min)":scores_df["Time_taken"].sum()/60,
                "Categorical_Columns": cat_cols, 
                "Numeric_Columns": num_cols,
                "n_cate_cols": len(cat_cols),
                "n_num_cols": len(num_cols),
                "total_cols": X.shape[1],
                "cate_prop": cate_prop,
                "num_prop":num_prop
                }

        metadata[df_name] = meta
        pipeline_dict[df_name] = pipelines

        print("===="*30)
        print(df_name)
        print("===="*30)
        pprint(meta)



        # except Exception as E:
        #     print("===="*30)
        #     print(f"{df_name}------>Failed")
        #     print()
        #     print(E)
        #     print("===="*30)

    
    with open(f"CE_BenchMark/Metadata/metadata.pkl", 'wb') as f:
        pickle.dump(metadata, f)


    return pipelines


now = datetime.datetime.now()

In [ ]:
df_new.tail()

       click    C1 banner_pos   site_id site_domain site_category    app_id app_domain app_category device_id device_ip device_model device_type device_conn_type    C14  C15  C16   C17 C18  C19     C20  C21 month dayofweek day hour  y
99994  False  1005  0          7294ea0f  863fa89d    3e814130      ecad2386  7801e8d9   07d7df22     a99f214a  783d53a5  04f5b394     1           0                17239  320  50   1973  3   39   100148  23   10    3         23  15   0
99995  False  1005  0          1fbe01fe  f3845767    28905ebd      ecad2386  7801e8d9   07d7df22     a99f214a  79117e3c  711ee120     1           0                22261  320  50   2545  0   167  100084  221  10    2         29  0    0
99996  True   1005  0          85f751fd  c4e18dd6    50e219e0      7358e05e  b9528b13   cef3e649     927c68c6  e774692b  1f0bc64f     1           0                21276  320  50   2443  2   39  -1       23   10    2         22  15   1
99997  True   1005  0          5b08c53b  7687a86e    3e814130      ecad2386  7801e8d9   07d7df22     a99f214a  4815ea13  d787e91b     1           0                20093  300  250  2295  2   35   100081  23   10    5         25  8    1
99998  False  1005  0          1fbe01fe  f3845767    28905ebd      ecad2386  7801e8d9   07d7df22     a99f214a  594a6636  5096d134     1           0                22677  320  50   2617  0   35  -1       51   10    1         28  1    0

In [ ]:
df_final = df_new.drop(columns=["click", "device_ip"])

In [ ]:
df_final.isnull().sum()

C1                  0
banner_pos          0
site_id             0
site_domain         0
site_category       0
app_id              0
app_domain          0
app_category        0
device_id           0
device_model        0
device_type         0
device_conn_type    0
C14                 0
C15                 0
C16                 0
C17                 0
C18                 0
C19                 0
C20                 0
C21                 0
month               0
dayofweek           0
day                 0
hour                0
y                   0
dtype: int64

In [ ]:
df_final.dropna(inplace=True)

In [ ]:
df_final.tail()

         C1 banner_pos   site_id site_domain site_category    app_id app_domain app_category device_id device_model device_type device_conn_type    C14  C15  C16   C17 C18  C19     C20  C21 month dayofweek day hour  y
99994  1005  0          7294ea0f  863fa89d    3e814130      ecad2386  7801e8d9   07d7df22     a99f214a  04f5b394     1           0                17239  320  50   1973  3   39   100148  23   10    3         23  15   0
99995  1005  0          1fbe01fe  f3845767    28905ebd      ecad2386  7801e8d9   07d7df22     a99f214a  711ee120     1           0                22261  320  50   2545  0   167  100084  221  10    2         29  0    0
99996  1005  0          85f751fd  c4e18dd6    50e219e0      7358e05e  b9528b13   cef3e649     927c68c6  1f0bc64f     1           0                21276  320  50   2443  2   39  -1       23   10    2         22  15   1
99997  1005  0          5b08c53b  7687a86e    3e814130      ecad2386  7801e8d9   07d7df22     a99f214a  d787e91b     1           0                20093  300  250  2295  2   35   100081  23   10    5         25  8    1
99998  1005  0          1fbe01fe  f3845767    28905ebd      ecad2386  7801e8d9   07d7df22     a99f214a  5096d134     1           0                22677  320  50   2617  0   35  -1       51   10    1         28  1    0

In [ ]:
df_final.shape

(99999, 25)

In [ ]:
df_final["y"] = df_final["y"].astype(int)

# Model Building

In [ ]:
df_final["y"].value_counts(normalize=True)

0    0.830198
1    0.169802
Name: y, dtype: float64

In [ ]:
datasets = OrderedDict()
datasets["CTR"]= df_final


targets = {
    "CTR": "y"
           }

In [ ]:
pipelines = CE_BenchMark_Pipeline(datasets, targets)

CTR
----------------------------->> Category Encoders instances created
------------------------------------->> ML Models instances created
Data Split --------------------->> X_train, X_test, y_train, y_test
CatBoostEncoder
Logistic Regression
--------------------------->> Evaluation of Model completed
ML Pipeline Successfully----------------->> CatBoostEncoder
Random Forest
--------------------------->> Evaluation of Model completed
ML Pipeline Successfully----------------->> CatBoostEncoder
XGBoost
--------------------------->> Evaluation of Model completed
ML Pipeline Successfully----------------->> CatBoostEncoder
--------------------->>>>>>>Successfully completed CE Benchmark
CountEncoder
Logistic Regression
--------------------------->> Evaluation of Model completed
ML Pipeline Successfully----------------->> CountEncoder
Random Forest
--------------------------->> Evaluation of Model completed
ML Pipeline Successfully----------------->> CountEncoder
XGBoost
--------------------------->> Evaluation of Model completed
ML Pipeline Successfully----------------->> CountEncoder
--------------------->>>>>>>Successfully completed CE Benchmark
LeaveOneOutEncoder
Logistic Regression
--------------------------->> Evaluation of Model completed
ML Pipeline Successfully----------------->> LeaveOneOutEncoder
Random Forest
--------------------------->> Evaluation of Model completed
ML Pipeline Successfully----------------->> LeaveOneOutEncoder
XGBoost
--------------------------->> Evaluation of Model completed
ML Pipeline Successfully----------------->> LeaveOneOutEncoder
--------------------->>>>>>>Successfully completed CE Benchmark
OrdinalEncoder
Logistic Regression
--------------------------->> Evaluation of Model completed
ML Pipeline Successfully----------------->> OrdinalEncoder
Random Forest
--------------------------->> Evaluation of Model completed
ML Pipeline Successfully----------------->> OrdinalEncoder
XGBoost
--------------------------->> Evaluation of Model completed
ML Pipeline Successfully----------------->> OrdinalEncoder
--------------------->>>>>>>Successfully completed CE Benchmark
TargetEncoder
Logistic Regression
--------------------------->> Evaluation of Model completed
ML Pipeline Successfully----------------->> TargetEncoder
Random Forest
--------------------------->> Evaluation of Model completed
ML Pipeline Successfully----------------->> TargetEncoder
XGBoost
--------------------------->> Evaluation of Model completed
ML Pipeline Successfully----------------->> TargetEncoder
--------------------->>>>>>>Successfully completed CE Benchmark
WOEEncoder
Logistic Regression
--------------------------->> Evaluation of Model completed
ML Pipeline Successfully----------------->> WOEEncoder
Random Forest
--------------------------->> Evaluation of Model completed
ML Pipeline Successfully----------------->> WOEEncoder
XGBoost
--------------------------->> Evaluation of Model completed
ML Pipeline Successfully----------------->> WOEEncoder
--------------------->>>>>>>Successfully completed CE Benchmark
---------->> Categorical Benchmark completed for CTR
========================================================================================================================
CTR
========================================================================================================================
{'Categorical_Columns': ['C1',
                         'banner_pos',
                         'site_id',
                         'site_domain',
                         'site_category',
                         'app_id',
                         'app_domain',
                         'app_category',
                         'device_id',
                         'device_model',
                         'device_type',
                         'device_conn_type',
                         'C14',
                         'C15',
                         'C16',
                         'C17',
                         'C18',
                         'C19',
                         'C20',
                         'C21',
                         'month',
                         'dayofweek',
                         'day',
                         'hour'],
 'Dataset': 'CTR',
 'Numeric_Columns': [],
 'cate_prop': 1.0,
 'n_cate_cols': 24,
 'n_num_cols': 0,
 'num_prop': 0.0,
 'total_cols': 24}

In [ ]:
set_config(display="diagram")
# click on the diagram below to see the details of each step
pipelines["WOEEncoder"][1]

Pipeline(steps=[('preprocessor',
                 ColumnTransformer(transformers=[('categorical',
                                                  Pipeline(steps=[('imputation_constant',
                                                                   SimpleImputer(fill_value='missing',
                                                                                 strategy='constant')),
                                                                  ('WOEEncoder',
                                                                   WOEEncoder())]),
                                                  ['site_id', 'site_domain',
                                                   'site_category', 'app_id',
                                                   'app_domain', 'app_category',
                                                   'device_id',
                                                   'device_model']),
                                                 ('numerical',
                                                  Pipeline(steps=[('imputation_mean',
                                                                   SimpleImputer()),
                                                                  ('scaler',
                                                                   StandardScaler())]),
                                                  ['C1', 'banner_pos',
                                                   'device_type',
                                                   'device_conn_type', 'C14',
                                                   'C15', 'C16', 'C17', 'C18',
                                                   'C19', 'C20', 'C21', 'month',
                                                   'dayofweek', 'day',
                                                   'hour'])])),
                ('classifier', RandomForestClassifier(random_state=42))])

### MLJar Feature Selection

In [ ]:
from sklearn.metrics import roc_auc_score
from supervised import AutoML

In [ ]:
df_final.head(3)

     C1 banner_pos   site_id site_domain site_category    app_id app_domain app_category device_id device_model device_type device_conn_type    C14  C15 C16   C17 C18  C19     C20  C21 month dayofweek day hour  y
0  1005  1          856e6d3f  58a89a43    f028772b      ecad2386  7801e8d9   07d7df22     a99f214a  be6db1d7     1           0                22683  320  50  2528  0   39   100075  221  10    1         28  14   0
1  1005  1          e151e245  7e091613    f028772b      ecad2386  7801e8d9   07d7df22     a99f214a  1b13b020     1           0                17037  320  50  1934  2   39  -1       16   10    2         22  19   1
2  1005  0          e3c09f3a  d262cf1e    28905ebd      ecad2386  7801e8d9   07d7df22     a99f214a  9a45a8e8     1           0                22155  320  50  2552  3   167  100202  23   10    3         23  18   0

In [ ]:
df_final.C1.nunique()

7

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(df[df.columns[:-1]], df["y"], test_size=0.25)

In [ ]:
automl = AutoML(mode="Compete")
automl.fit(X_train, y_train)

Linear algorithm was disabled.
AutoML directory: AutoML_1
The task is binary_classification with evaluation metric logloss
AutoML will use algorithms: ['Decision Tree', 'Random Forest', 'Extra Trees', 'LightGBM', 'Xgboost', 'CatBoost', 'Neural Network', 'Nearest Neighbors']
AutoML will stack models
AutoML will ensemble available models
AutoML steps: ['adjust_validation', 'simple_algorithms', 'default_algorithms', 'not_so_random', 'mix_encoding', 'golden_features', 'kmeans_features', 'insert_random_feature', 'features_selection', 'hill_climbing_1', 'hill_climbing_2', 'boost_on_errors', 'ensemble', 'stack', 'ensemble_stacked']
* Step adjust_validation will try to check up to 1 model

elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison

There was an error during 1_DecisionTree training.
Please check AutoML_1/errors.md for details.
* Step simple_algorithms will try to check up to 3 models

elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison

There was an error during 1_DecisionTree training.
Please check AutoML_1/errors.md for details.

elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison

There was an error during 2_DecisionTree training.
Please check AutoML_1/errors.md for details.

elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison

There was an error during 3_DecisionTree training.
Please check AutoML_1/errors.md for details.
* Step default_algorithms will try to check up to 7 models

elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison

There was an error during 1_Default_LightGBM training.
Please check AutoML_1/errors.md for details.

elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison

There was an error during 2_Default_Xgboost training.
Please check AutoML_1/errors.md for details.
3_Default_CatBoost logloss 8.9e-05 trained in 40.08 seconds

elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison

There was an error during 4_Default_NeuralNetwork training.
Please check AutoML_1/errors.md for details.

elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison

There was an error during 5_Default_RandomForest training.
Please check AutoML_1/errors.md for details.

elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison

There was an error during 6_Default_ExtraTrees training.
Please check AutoML_1/errors.md for details.

elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison

There was an error during 7_Default_NearestNeighbors training.
Please check AutoML_1/errors.md for details.
* Step not_so_random will try to check up to 63 models

elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison

There was an error during 11_LightGBM training.
Please check AutoML_1/errors.md for details.

elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison

There was an error during 2_Xgboost training.
Please check AutoML_1/errors.md for details.
20_CatBoost logloss 5.2e-05 trained in 1044.12 seconds

elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison

There was an error during 29_RandomForest training.
Please check AutoML_1/errors.md for details.

elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison

There was an error during 38_ExtraTrees training.
Please check AutoML_1/errors.md for details.

elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison

There was an error during 47_NeuralNetwork training.
Please check AutoML_1/errors.md for details.

elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison

There was an error during 56_NearestNeighbors training.
Please check AutoML_1/errors.md for details.

elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison

There was an error during 12_LightGBM training.
Please check AutoML_1/errors.md for details.

elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison

There was an error during 3_Xgboost training.
Please check AutoML_1/errors.md for details.
21_CatBoost logloss 6.6e-05 trained in 44.56 seconds

elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison

There was an error during 30_RandomForest training.
Please check AutoML_1/errors.md for details.

elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison

There was an error during 39_ExtraTrees training.
Please check AutoML_1/errors.md for details.

elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison

There was an error during 48_NeuralNetwork training.
Please check AutoML_1/errors.md for details.

elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison

There was an error during 57_NearestNeighbors training.
Please check AutoML_1/errors.md for details.

elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison

There was an error during 13_LightGBM training.
Please check AutoML_1/errors.md for details.

elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison

There was an error during 4_Xgboost training.
Please check AutoML_1/errors.md for details.
22_CatBoost logloss 5.4e-05 trained in 48.57 seconds

elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison

There was an error during 31_RandomForest training.
Please check AutoML_1/errors.md for details.

elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison

There was an error during 40_ExtraTrees training.
Please check AutoML_1/errors.md for details.

elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison

There was an error during 49_NeuralNetwork training.
Please check AutoML_1/errors.md for details.

elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison

There was an error during 58_NearestNeighbors training.
Please check AutoML_1/errors.md for details.

elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison

There was an error during 14_LightGBM training.
Please check AutoML_1/errors.md for details.

elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison

There was an error during 5_Xgboost training.
Please check AutoML_1/errors.md for details.
23_CatBoost logloss 5.2e-05 trained in 47.09 seconds

elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison

There was an error during 32_RandomForest training.
Please check AutoML_1/errors.md for details.

elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison

There was an error during 41_ExtraTrees training.
Please check AutoML_1/errors.md for details.

elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison

There was an error during 50_NeuralNetwork training.
Please check AutoML_1/errors.md for details.

elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison

There was an error during 59_NearestNeighbors training.
Please check AutoML_1/errors.md for details.

elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison

There was an error during 15_LightGBM training.
Please check AutoML_1/errors.md for details.

elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison

There was an error during 6_Xgboost training.
Please check AutoML_1/errors.md for details.
24_CatBoost logloss 2.2e-05 trained in 708.63 seconds
Skip mix_encoding because no parameters were generated.
Skip golden_features because of the time limit.
Skip kmeans_features because of the time limit.
* Step insert_random_feature will try to check up to 1 model
23_CatBoost_RandomFeature logloss 0.000111 trained in 67.38 seconds
Drop features ['device_conn_type', 'device_ip_9343cb87', 'C18', 'site_category', 'app_category', 'device_model', 'C21', 'C20', 'C17', 'C14', 'site_id', 'device_id', 'app_domain', 'app_id', 'site_domain', 'hour', 'day', 'device_ip_0accc299', 'device_ip_009a7861', 'device_ip_0489ce3f', 'device_ip_07875ea4', 'device_ip_086ef670', 'device_ip_285aa37d', 'device_ip_10dcdfb1', 'device_ip_19b4af68', 'device_ip_1aea2343', 'device_ip_ff1c4f79', 'device_ip_207f3ea6', 'device_ip_211f96b8', 'device_ip_225af2a8', 'device_ip_54d0fa93', 'device_ip_1cf29716', 'device_ip_2bb4af67', 'device_ip_46b1dc9f', 'device_ip_2d7a20eb', 'device_ip_2e08e353', 'device_ip_2e93a860', 'device_ip_2f323f36', 'device_ip_31f8e95a', 'device_ip_348533f2', 'device_ip_3c82662a', 'device_ip_3d1c020c', 'device_ip_3e44041f', 'device_ip_431b3174', 'device_ip_488a9a3e', 'device_ip_478ce7c1', 'device_ip_47a733b8', 'device_ip_6394f6f6', 'device_ip_2b479ec6', 'device_ip_4cf55065', 'device_ip_699f69bd', 'device_ip_693bff3e', 'device_ip_52e933ed', 'device_ip_6fdf1afa', 'device_ip_57cd4006', 'device_ip_59ac940d', 'device_ip_6b9769f2', 'device_ip_75bb1b58', 'device_ip_be7092cb', 'device_ip_bd7006aa', 'device_ip_a7f3ffed', 'device_ip_7eeac961', 'device_ip_80e2134e', 'device_ip_877c72d4', 'device_ip_884297d2', 'device_ip_8a014cbb', 'device_ip_930ec31d', 'device_ip_93180936', 'device_ip_95b2935e', 'device_ip_9b13a699', 'device_ip_9b1fe278', 'device_ip_a1e99bce', 'device_ip_a6df415d', 'device_ip_79a1617b', 'device_ip_a8536f3a', 'device_ip_aa42be81', 'device_ip_ac77b71a', 'device_ip_af4a9787', 'device_ip_af62faf4', 'device_ip_af9205f9', 'device_ip_b0070d9a', 'device_ip_b4a0ec64', 'device_ip_b79e1ece', 'device_ip_b83fa2a1', 'device_ip_bca8f26d', 'device_ip_7ed30f6c', 'device_ip_bf2f7567', 'device_ip_c41fe74f', 'device_ip_e20f2e41', 'device_ip_fde01da8', 'device_ip_c64f8ed3', 'device_ip_c6563308', 'device_ip_c8733a0f', 'device_ip_ceffea69', 'device_ip_d0a8a201', 'device_ip_d0e9d4d1', 'device_ip_d2b32c84', 'device_ip_d90a7774', 'device_ip_dab29f53', 'device_ip_ddd2926e', 'device_ip_e0030fa7', 'device_ip_e30e04df', 'device_ip_e54c1344', 'device_ip_e6a00ba6', 'device_ip_e960ae63', 'device_ip_e99c4df5', 'device_ip_e9d5636f', 'device_ip_f077459c', 'device_ip_f0f99058', 'device_ip_f46f0a98', 'device_ip_f6cd8d52', 'device_ip_f7853e5a', 'device_ip_f7b1ef1e', 'device_ip_fadf993c', 'device_ip_c5d4327c', 'dayofweek', 'C1', 'device_type', 'device_ip_a2d72242', 'random_feature']
* Step features_selection will try to check up to 1 model
23_CatBoost_SelectedFeatures logloss 3.1e-05 trained in 11.41 seconds
* Step hill_climbing_1 will try to check up to 5 models
25_CatBoost logloss 2.6e-05 trained in 504.76 seconds
* Step hill_climbing_2 will try to check up to 3 models
26_CatBoost logloss 4.4e-05 trained in 724.62 seconds
Skip boost_on_errors because of the time limit.
* Step ensemble will try to check up to 1 model
Ensemble logloss 2.2e-05 trained in 2.31 seconds
* Step stack will try to check up to 9 models
24_CatBoost_Stacked logloss 4.4e-05 trained in 746.08 seconds
* Step ensemble_stacked will try to check up to 1 model
Ensemble_Stacked logloss 2.2e-05 trained in 2.56 seconds
AutoML fit time: 4330.6 seconds
AutoML best model: Ensemble_Stacked

AutoML(mode='Compete')

In [ ]:
print("Test Accuracy:", automl.score(X_test, y_test))

Test Accuracy: 0.8304

In [ ]:
from sklearn.metrics import roc_auc_score

In [ ]:
 from sklearn.metrics import f1_score
 y_pred = automl.predict(X_test)
 f1_score(y_test, y_pred, zero_division=1)
 print(f"F1: {f1_score(y_test, y_pred, zero_division=1):.2f}%")

F1: 0.00%

In [ ]:
f1_score(y_test, y_pred, zero_division=1)

0.0

In [ ]:
y_pred

array([0, 0, 0, ..., 0, 0, 0])

In [ ]:
 from sklearn.metrics import precision_recall_fscore_support